### ISSUE TITLE
Set up automated Flux commands reference

### ISSUE THREAD

**Issue by fsteeg** [metafacture/metafacture.github.io#10]
Like [flux-commands.md](https://github.com/metafacture/metafacture-documentation/blob/master/flux-commands.md) (which is basically the output of `sh flux.sh > flux-commands.md`, see https://github.com/metafacture/metafacture-core/commit/4d80ab4a87eed552fb36de722765c2f1ae6e7923), but:

- [ ] Improve flux-commands.md content (group commands by type, explain signatures -> https://github.com/metafacture/metafacture-documentation/issues/16, add missing options) -> https://github.com/metafacture/metafacture-core/issues/367
- [ ] Automated creation and publishing of flux-commands.md with GitHub Actions (triggered by metafacture-core releases) -> https://github.com/metafacture/metafacture-core/issues/368
- [ ] Add filtering support, e.g. generate filter 'buttons' for each type as input and output, e.g. `->StreamReceiver` for all decoders, `StreamReceiver->` for all encoders, etc. -> https://github.com/metafacture/metafacture-core/issues/369

**Comment by TobiasNx** [comment]
Sorting of the list perhaps should be sorted by input not by alphabet.
